name: Common CI Workflow

on:
  workflow_call:
    inputs:
      run-translations:
        required: true
        type: boolean
      pack:
        required: true
        type: boolean

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install dependencies
        run: | 
          npm install @octokit/auth-app
          npm install @actions/core

    - name: Run translations
      if: ${{ inputs.run-translations }}
      run: echo "running translations"

    - name: Pack
      if: ${{ inputs.pack }}
      run: echo "packing library"

    - name: Get Installation Access Token
        id: get_installation_token
        run: node .github/workflows/get-installation-token.mjs
        env:
          APP_ID: ${{ secrets.APP_ID_2 }}
          INSTALLATION_ID: ${{ secrets.INSTALLATION_ID_2 }}
          PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY_2 }}

    - name: Notify author on failure
      if: ${{ failure() }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.steps.get_installation_token.outputs.token }}
        script: |
          const prNumber = context.payload.pull_request.number;
          const prAuthor = context.payload.pull_request.user.login;
          const repoOwner = context.repo.owner;
          const repoName = context.repo.repo;
          await github.rest.issues.createComment({
            owner: repoOwner,
            repo: repoName,
            issue_number: prNumber,
            body: `@${prAuthor}, the workflow has failed. Please check the logs for details.`
          });