name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      run-translations:
        required: true
        type: boolean

jobs:
  Validate-translations:
    runs-on: ubuntu-latest
    if: ${{ inputs.run-translations }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Clone h5p-cli repository
        run: git clone --branch fix/JI-6520-improve-empty-object-filtering https://github.com/h5p/h5p-cli.git
      - name: Install h5p-cli from specific branch
        run: |
          cd h5p-cli
          npm install
          cd ..
          npm install -g ./h5p-cli
      - name: Validate translations
        run: |
          libDir=${PWD##*/}
          cd ..
          h5p utils validate "${libDir}"