name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      run-translations:
        required: true
        type: boolean

jobs:
  Validate-translations:
    runs-on: ubuntu-latest
    if: ${{ inputs.run-translations }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install h5p cli
        run: npm install h5p-cli
      - name: Validate translations
        run: |
          libDir=${PWD##*/}
          cd ..
          ./node_modules/.bin/h5p utils validate "${libDir}"