name: Common CI Workflow

on:
  workflow_call:
    inputs:
      run-translations:
        required: true
        type: boolean
      pack:
        required: true
        type: boolean
    outputs:
      failure: 
        description: "status of reusable workflow"
        value: ${{ jobs.reusable-workflow.outputs.failure-notice }}

jobs:
  reusable-workflow:
    runs-on: ubuntu-latest
    outputs:
      failure-notice: ${{ steps.status.outputs.failure }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run translations
      if: ${{ inputs.run-translations }}
      run: echo "running translations"

    - name: Pack
      if: ${{ inputs.pack }}
      run: echo "packing library"

    - name: Set failure message
      id: status
      if: ${{ success() }}
      run: echo "failure=true" >> $GITHUB_OUTPUT
